/** Noyau vérifié SYSCOHADA révisé. L'import officiel le complète sans l'écraser. */
export type SyscohadaReference = {
  code: string; libelle: string; classe: number; nature: string;
  sensNormal: string; postable: boolean; splittable: boolean; source: string;
};

type R = [string, string, number, string, string, boolean];
const SOURCE = "SYSCOHADA révisé — Acte uniforme OHADA";
const rows: R[] = [
  ["10","Capital",1,"BILAN","CREDIT",false],["101","Capital social",1,"BILAN","CREDIT",true],["11","Réserves",1,"BILAN","CREDIT",false],["111","Réserve légale",1,"BILAN","CREDIT",true],["12","Report à nouveau",1,"BILAN","CREDIT",true],["13","Résultat net de l'exercice",1,"BILAN","CREDIT",true],["16","Emprunts et dettes assimilées",1,"BILAN","CREDIT",false],["162","Emprunts auprès des établissements de crédit",1,"BILAN","CREDIT",true],
  ["21","Immobilisations incorporelles",2,"BILAN","DEBIT",false],["211","Frais de développement",2,"BILAN","DEBIT",true],["213","Logiciels et licences",2,"BILAN","DEBIT",true],["22","Immobilisations corporelles",2,"BILAN","DEBIT",false],["221","Terrains",2,"BILAN","DEBIT",true],["222","Bâtiments",2,"BILAN","DEBIT",true],["24","Matériel, outillage, mobilier et matériel de transport",2,"BILAN","DEBIT",false],["241","Matériel industriel et outillage",2,"BILAN","DEBIT",true],["245","Matériel de transport",2,"BILAN","DEBIT",true],["28","Amortissements",2,"BILAN","CREDIT",false],["281","Amort. des immobilisations incorporelles",2,"BILAN","CREDIT",true],["282","Amort. des immobilisations corporelles",2,"BILAN","CREDIT",true],
  ["31","Marchandises",3,"BILAN","DEBIT",false],["311","Marchandises A",3,"BILAN","DEBIT",true],["32","Matières premières et fournitures liées",3,"BILAN","DEBIT",false],["39","Dépréciations des stocks",3,"BILAN","CREDIT",false],["391","Dépréciations des marchandises",3,"BILAN","CREDIT",true],
  ["40","Fournisseurs et comptes rattachés",4,"BILAN","CREDIT",false],["401","Fournisseurs d'exploitation",4,"BILAN","CREDIT",true],["404","Fournisseurs d'immobilisations",4,"BILAN","CREDIT",true],["41","Clients et comptes rattachés",4,"BILAN","DEBIT",false],["411","Clients ordinaires",4,"BILAN","DEBIT",true],["416","Clients douteux ou litigieux",4,"BILAN","DEBIT",true],["42","Personnel",4,"BILAN","CREDIT",false],["421","Rémunérations dues",4,"BILAN","CREDIT",true],["43","Organismes sociaux",4,"BILAN","CREDIT",false],["431","CNSS",4,"BILAN","CREDIT",true],["438","AMU",4,"BILAN","CREDIT",true],["44","État et collectivités publiques",4,"BILAN","CREDIT",false],["441","État, impôt sur les bénéfices (IS)",4,"BILAN","CREDIT",true],["442","État, retenues à la source (IRPP)",4,"BILAN","CREDIT",true],["445","État, TVA",4,"BILAN","CREDIT",false],["4452","TVA collectée",4,"BILAN","CREDIT",true],["4454","TVA déductible",4,"BILAN","DEBIT",true],["4456","TVA à décaisser",4,"BILAN","CREDIT",true],["447","État, patente et autres impôts",4,"BILAN","CREDIT",true],["47","Comptes transitoires et de régularisation",4,"BILAN","DEBIT",false],["471","Comptes d'attente — débit",4,"BILAN","DEBIT",true],["472","Comptes d'attente — crédit",4,"BILAN","CREDIT",true],["48","Comptes de régularisation",4,"BILAN","DEBIT",false],["486","Charges à payer",4,"BILAN","CREDIT",true],["487","Produits à recevoir",4,"BILAN","DEBIT",true],
  ["52","Banques",5,"BILAN","DEBIT",false],["521","Banques",5,"BILAN","DEBIT",true],["57","Caisse",5,"BILAN","DEBIT",false],["571","Caisse",5,"BILAN","DEBIT",true],
  ["60","Achats et variations de stocks",6,"RESULTAT","DEBIT",false],["601","Achats de marchandises",6,"RESULTAT","DEBIT",true],["602","Achats de matières premières",6,"RESULTAT","DEBIT",true],["62","Services extérieurs et autres charges",6,"RESULTAT","DEBIT",false],["621","Loyers et charges locatives",6,"RESULTAT","DEBIT",true],["63","Impôts, taxes et versements assimilés",6,"RESULTAT","DEBIT",false],["631","Impôts et taxes (dont patente)",6,"RESULTAT","DEBIT",true],["66","Charges de personnel",6,"RESULTAT","DEBIT",false],["661","Rémunérations directes versées aux salariés",6,"RESULTAT","DEBIT",true],["663","Charges sociales patronales",6,"RESULTAT","DEBIT",true],["67","Dotations aux amortissements et provisions",6,"RESULTAT","DEBIT",false],["671","Dotations aux amortissements",6,"RESULTAT","DEBIT",true],["69","Impôts sur le résultat",6,"RESULTAT","DEBIT",false],["691","Impôt sur les sociétés",6,"RESULTAT","DEBIT",true],
  ["70","Ventes et prestations",7,"RESULTAT","CREDIT",false],["701","Ventes de marchandises",7,"RESULTAT","CREDIT",true],["702","Ventes de produits finis",7,"RESULTAT","CREDIT",true],["77","Revenus financiers",7,"RESULTAT","CREDIT",false],["78","Reprises de provisions et dépréciations",7,"RESULTAT","CREDIT",false],["79","Transferts de charges",7,"RESULTAT","CREDIT",false],
  ["81","Engagements obtenus",8,"HORS_BILAN","CREDIT",false],["86","Engagements accordés",8,"HORS_BILAN","DEBIT",false],
];

export const SYSCOHADA_REF: SyscohadaReference[] = rows.map(([code, libelle, classe, nature, sensNormal, postable]) => ({ code, libelle, classe, nature, sensNormal, postable, splittable: true, source: SOURCE }));
